# Generated by Django 2.2.9 on 2020-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Your_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('Your_Post_title', models.CharField(max_length=200)),
                ('Your_Post', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
